# git-cliff configuration file
# https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog
"""
body = """
{% if version -%}
## {{ version | split(pat="@") | last }} ({{ timestamp | date(format="%b %e, %Y") | trim }})
{% else -%}
## Unreleased
{% endif -%}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits -%}
- {{ commit.message | split(pat="\n") | first | trim }}
{% endfor %}
{% endfor -%}
"""
footer = """
{% for release in releases -%}
{% if release.version -%}
{% if release.previous.version -%}
[{{ release.version | split(pat="@") | last }}]: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ release.previous.version }}...{{ release.version }}
{% else -%}
[{{ release.version | split(pat="@") | last }}]: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/releases/tag/{{ release.version }}
{% endif -%}
{% else -%}
[Unreleased]: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ release.previous.version }}...HEAD
{% endif -%}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^docs", group = "Changed" },
  { message = "^perf", group = "Changed" },
  { message = "^refactor", group = "Changed" },
  { message = "^style", group = "Changed" },
  { message = "^test", group = "Changed" },
  { message = "^build", group = "Changed" },
  { message = "^ci", group = "Changed" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore\\(deps", skip = true },
  { message = "^chore", group = "Changed" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = ".*@\\d+\\.\\d+\\.\\d+(?:-[0-9A-Za-z.-]+)?"
sort_commits = "oldest"
