sonar.projectKey=agrawal-rohit_tuckshop
sonar.organization=agrawal-rohit
sonar.sources=packages/cli/src,packages/core/src
sonar.tests=packages/cli/src,packages/core/src
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/*.test.ts,**/dist/**
sonar.coverage.exclusions=**/*.test.ts,**/bin/**,**/docs/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info