sonar.projectKey=agrawal-rohit_tuckshop
sonar.organization=agrawal-rohit
sonar.sources=packages
sonar.exclusions=**/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.projectVersion=0.2.1
