import { describe, expect, it } from "vitest";
import * as core from "./index";

describe("package entry", () => {
	it("re-exports the public core API", () => {
		expect(typeof core.isFileAsync).toBe("function");
		expect(typeof core.isMissingPathError).toBe("function");
		expect(typeof core.pathKindAsync).toBe("function");
		expect(core.PathKind).toBeDefined();
		expect(typeof core.readFileAsync).toBe("function");
		expect(typeof core.readJsonFileAsync).toBe("function");
		expect(core.InvalidJsonError).toBeDefined();
		expect(typeof core.writeFileAsync).toBe("function");
		expect(typeof core.isAbsoluteHttpUrl).toBe("function");
		expect(typeof core.assertSafeRemoteUrl).toBe("function");
		expect(typeof core.publishedRegistryUrl).toBe("function");
		expect(typeof core.parseRegistryDocument).toBe("function");
		expect(typeof core.parseWithSchema).toBe("function");
		expect(typeof core.buildRegistry).toBe("function");
		expect(typeof core.buildInstallPlan).toBe("function");
		expect(typeof core.runAsync).toBe("function");
		expect(typeof core.mergeEcosystemMaps).toBe("function");
		expect(typeof core.mergeDependencySet).toBe("function");
		expect(typeof core.mergeCommandSet).toBe("function");
		expect(typeof core.buildPackageInstallCommands).toBe("function");
		expect(typeof core.collectDeclaredScriptUris).toBe("function");
		expect(typeof core.createRejectedScriptExecutor).toBe("function");
		expect(typeof core.joinRelativePathUnderRoot).toBe("function");
		expect(typeof core.isEscapingRelativePath).toBe("function");
		expect(typeof core.isNonRelativePath).toBe("function");
		expect(typeof core.detectPackageManagerFromLockfile).toBe("function");
		expect(typeof core.selectPackageManager).toBe("function");
		expect(typeof core.catalogNeedsPackageManager).toBe("function");
		expect(typeof core.packageManagerDropsCandidateDependsOn).toBe("function");
		expect(typeof core.compiledItemUsesEcosystem).toBe("function");
		expect(typeof core.packageManagerBindings).toBe("function");
		expect(typeof core.isPackageManagerForEcosystem).toBe("function");
		expect(typeof core.packageManagerSpec).toBe("function");
		expect(typeof core.runArgvAsync).toBe("function");
		expect(core.PACKAGE_MANAGER_KEY).toBe("packageManager");
		expect(typeof core.policyForConditionKind).toBe("function");
		expect(typeof core.runBeforeWriteHook).toBe("function");
		expect(typeof core.runAfterInstallHook).toBe("function");
		expect(typeof core.inferConditionDefault).toBe("function");
		expect(typeof core.buildInterpolationContext).toBe("function");
		expect(typeof core.interpolateCompiledItem).toBe("function");
		expect(typeof core.reservedInterpolationKeys).toBe("function");
		expect(typeof core.mergeSecretNames).toBe("function");
		expect(typeof core.uniqueSorted).toBe("function");
		expect(typeof core.compiledItem).toBe("function");
		expect(typeof core.foldCompiledItems).toBe("function");
		expect(typeof core.mergeCompiledItemFields).toBe("function");
		expect(typeof core.assertUniqueCompiledItemTargets).toBe("function");
		expect(typeof core.runInstallHookOptions).toBe("function");
		expect(typeof core.collectItemLocalConditions).toBe("function");
		expect(typeof core.packWhenUsesCapturedKeys).toBe("function");
		expect(typeof core.collectRequiredConditions).toBe("function");
		expect(typeof core.collectRequiredConditionWave).toBe("function");
		expect(typeof core.uniqueKnownRegistryItems).toBe("function");
		expect(core.compiledItemSchema).toBeDefined();
		expect(core.RegistryConditionKind).toBeDefined();
		expect(core.RegistryEcosystem).toBeDefined();
	});
});
