import { describe, expect, it } from "vitest";
import * as core from "./index";

describe("package entry", () => {
	it("re-exports the public core API", () => {
		expect(typeof core.isFileAsync).toBe("function");
		expect(typeof core.pathKindAsync).toBe("function");
		expect(core.PathKind).toBeDefined();
		expect(typeof core.readFileAsync).toBe("function");
		expect(typeof core.readJsonFileAsync).toBe("function");
		expect(core.InvalidJsonError).toBeDefined();
		expect(typeof core.writeFileAsync).toBe("function");
		expect(typeof core.isAbsoluteHttpUrl).toBe("function");
		expect(typeof core.assertSafeRemoteUrl).toBe("function");
		expect(typeof core.publishedRegistryUrl).toBe("function");
		expect(typeof core.parseRegistryDocument).toBe("function");
		expect(typeof core.parseWithSchema).toBe("function");
		expect(typeof core.buildRegistry).toBe("function");
		expect(typeof core.buildInstallPlan).toBe("function");
		expect(typeof core.runAsync).toBe("function");
		expect(typeof core.mergeEcosystemMaps).toBe("function");
		expect(typeof core.mergeDependencySet).toBe("function");
		expect(typeof core.mergeCommandSet).toBe("function");
		expect(typeof core.buildPackageInstallCommands).toBe("function");
		expect(typeof core.collectDeclaredScriptUris).toBe("function");
		expect(typeof core.joinRelativePathUnderRoot).toBe("function");
		expect(typeof core.detectPackageManagerFromLockfile).toBe("function");
		expect(typeof core.selectNpmPackageManager).toBe("function");
		expect(typeof core.packageManagerBindings).toBe("function");
		expect(typeof core.isNpmPackageManager).toBe("function");
		expect(core.PACKAGE_MANAGER_KEY).toBe("packageManager");
		expect(typeof core.policyForConditionKind).toBe("function");
		expect(typeof core.runPrepareInstallHook).toBe("function");
		expect(typeof core.runFinalizeInstallHook).toBe("function");
		expect(typeof core.inferConditionDefault).toBe("function");
		expect(typeof core.buildInterpolationContext).toBe("function");
		expect(typeof core.interpolateCompiledItem).toBe("function");
		expect(typeof core.mergeSecretNames).toBe("function");
		expect(typeof core.collectItemLocalConditions).toBe("function");
		expect(core.compiledItemSchema).toBeDefined();
		expect(core.RegistryConditionKind).toBeDefined();
		expect(core.RegistryEcosystem).toBeDefined();
	});
});
