export { type BuildRegistryOptions, buildRegistry } from "./build";
export {
	type ConditionKindPolicy,
	policyForConditionKind,
	RegistryConditionKind,
	type RegistryContext,
	type RegistryContextValue,
	type RegistryWhenValue,
} from "./condition-kind";
export {
	InvalidJsonError,
	isFileAsync,
	PathKind,
	pathKindAsync,
	readFileAsync,
	readJsonFileAsync,
	writeFileAsync,
} from "./fs";
export type {
	ConditionHandler,
	ConditionHandlerContext,
	FinalizeInstallHook,
	HandlerRuntime,
	HandlerSelectOption,
	InstallHookContext,
	PrepareInstallHook,
	PrepareInstallHookResult,
	PromptHost,
	RunInstallHookOptions,
} from "./handlers";
export {
	createHandlerRuntime,
	getScriptExecutor,
	inferConditionDefault,
	localScriptPath,
	runFinalizeInstallHook,
	runPrepareInstallHook,
	setScriptExecutor,
} from "./handlers";
export {
	buildInterpolationContext,
	type InterpolationView,
	interpolateCompiledItem,
} from "./interpolate";
export {
	buildPackageInstallCommands,
	detectPackageManagerFromLockfile,
	ecosystemManagers,
	isNpmPackageManager,
	mergeCommandSet,
	mergeDependencySet,
	mergeEcosystemMaps,
	mergeSecretNames,
	NpmPackageManager,
	PACKAGE_MANAGER_KEY,
	type PackageManagerBindings,
	type PackageManagerSpec,
	packageManagerBindings,
	type RegistryPackageManager,
	selectNpmPackageManager,
} from "./packages";
export { parseRegistryDocument, parseWithSchema } from "./parse";
export {
	assumeContextFromSelectedItems,
	buildInstallPlan,
	collectItemLocalConditions,
	collectRegistryDependencies,
	collectRequiredConditions,
	type IndexEntry,
	type InstallNode,
	type RequiredCondition,
} from "./plan";
export {
	assertConditionMapBindingKeys,
	type CompiledItem,
	type CompiledItemFile,
	compiledItemFileSchema,
	compiledItemSchema,
	type IndexItem,
	type IndexPack,
	indexItemSchema,
	indexPackSchema,
	type RawRegistryItem,
	type RawRegistryPack,
	type Registry,
	type RegistryCommandSet,
	type RegistryCondition,
	type RegistryConditionValue,
	RegistryDependencyKind,
	type RegistryDependencySet,
	RegistryEcosystem,
	type RegistryEcosystemCommands,
	type RegistryEcosystemDependencies,
	type RegistryFile,
	type RegistryItemTypeDefinition,
	type RegistryWhen,
	registryConditionSchema,
	registryConditionValueSchema,
	registryDependencySetSchema,
	registryDocumentFieldsSchema,
	registryEcosystemDependenciesSchema,
	registryFileSchema,
	registryItemSchema,
	registryItemTypeSchema,
	registryPackSchema,
	registryWhenSchema,
	registryWhenValueSchema,
} from "./schema";
export {
	assertIntegrityMatch,
	assertScriptsAllowed,
	type CreateScriptExecutorOptions,
	classifyRegistryTrust,
	collectDeclaredScriptUris,
	createScriptExecutor,
	INTEGRITY_PREFIX,
	loadSandboxedModule,
	RegistryTrust,
	resolveSandboxRunnerPath,
	type ScriptExecutor,
	sha256Integrity,
	verifyItemIntegrity,
	verifyScriptIntegrity,
} from "./scripts";
export { type RunOptions, runAsync } from "./shell";
export {
	assertSafeRemoteUrl,
	assertSameOriginIndexSource,
	isAbsoluteHttpUrl,
	joinIndexSource,
	joinRelativePathUnderRoot,
	publishedRegistryUrl,
} from "./urls";
