import type {
	BeforeWriteHook,
	CompiledItemFile,
} from "@cheetos/core";
import {
	escapeDoubleQuotedYaml,
	extractMarkdownFrontmatter,
	stripMatchingQuotes,
	parseYamlStringList,
	SUPPORTED_CODING_AGENT_IDES,
	type SupportedCodingAgentIDE,
} from "../transform-shared";

/** Frontmatter parsed from a Cursor `.mdc` rule file. */
export interface CursorRuleFrontmatter {
	description?: string;
	globs?: string[];
	alwaysApply?: boolean;
}

/**
 * Parse the value of the `globs` frontmatter field, including any continuation block-list lines.
 * @param inlineVal - Inline value after `globs:` on the same line.
 * @param lines - All frontmatter lines.
 * @param currentIndex - Index of the `globs:` line within `lines`.
 * @returns Parsed globs array and how many additional lines were consumed.
 */
function readGlobsField(
	inlineVal: string,
	lines: string[],
	currentIndex: number,
): { globs?: string[]; consumed: number } {
	const trimmed = inlineVal.trim();
	if (trimmed.startsWith("[")) {
		return { globs: parseYamlStringList(trimmed), consumed: 0 };
	}
	if (trimmed.length > 0) {
		return { globs: [stripMatchingQuotes(trimmed)], consumed: 0 };
	}

	const blockLines: string[] = [];
	let consumed = 0;
	while (
		currentIndex + 1 + consumed < lines.length &&
		/^\s+-\s+/.test(lines[currentIndex + 1 + consumed])
	) {
		blockLines.push(lines[currentIndex + 1 + consumed]);
		consumed++;
	}

	return {
		globs:
			blockLines.length > 0
				? parseYamlStringList(blockLines.join("\n"))
				: undefined,
		consumed,
	};
}

/**
 * Parse a Cursor `.mdc` rule document into frontmatter metadata and markdown body.
 * @param content - Full `.mdc` file content.
 * @returns Parsed frontmatter and markdown body.
 */
export function parseCursorRuleDocument(content: string): {
	frontmatter: CursorRuleFrontmatter;
	body: string;
} {
	const { frontmatterRaw, body } = extractMarkdownFrontmatter(content);
	if (!frontmatterRaw) return { frontmatter: {}, body };

	const frontmatter: CursorRuleFrontmatter = {};
	const lines = frontmatterRaw.split("\n");

	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];

		const descMatch = /^\s*description\s*:\s*(.+)$/.exec(line);
		if (descMatch) {
			frontmatter.description = stripMatchingQuotes(descMatch[1]);
			continue;
		}

		const applyMatch = /^\s*alwaysApply\s*:\s*(true|false)\s*$/.exec(line);
		if (applyMatch) {
			frontmatter.alwaysApply = applyMatch[1] === "true";
			continue;
		}

		const globsMatch = /^\s*globs\s*:\s*(.*)$/.exec(line);
		if (globsMatch) {
			const { globs, consumed } = readGlobsField(globsMatch[1], lines, i);
			if (globs) frontmatter.globs = globs;
			i += consumed;
		}
	}

	return { frontmatter, body };
}

/** Render an untouched Cursor `.mdc` rule at its canonical destination. */
function renderCursorRule(ruleContent: string, ruleName: string): {
	target: string;
	content: string;
} {
	return {
		target: `.cursor/rules/${ruleName}.mdc`,
		content: ruleContent,
	};
}

/** Render a Claude Code rule from Cursor frontmatter. */
function renderClaudeCodeRule(ruleContent: string, ruleName: string): {
	target: string;
	content: string;
} {
	const { frontmatter, body } = parseCursorRuleDocument(ruleContent);
	const description = frontmatter.description ?? ruleName;
	const pathLines = (frontmatter.globs ?? [])
		.map((glob) => `  - "${escapeDoubleQuotedYaml(glob)}"`)
		.join("\n");
	const paths = pathLines.length > 0 ? `\npaths:\n${pathLines}` : "";
	return {
		target: `.claude/rules/${ruleName}.md`,
		content: `---\ndescription: "${escapeDoubleQuotedYaml(description)}"${paths}\n---\n\n${body}`,
	};
}

/** Render a GitHub Copilot instruction file from Cursor frontmatter. */
function renderCopilotRule(ruleContent: string, ruleName: string): {
	target: string;
	content: string;
} {
	const { frontmatter, body } = parseCursorRuleDocument(ruleContent);
	const applyTo = frontmatter.globs?.[0] ?? "**/*";
	return {
		target: `.github/instructions/${ruleName}.instructions.md`,
		content: `---\napplyTo: "${escapeDoubleQuotedYaml(applyTo)}"\n---\n\n${body}`,
	};
}

/**
 * Render an OpenAI Codex or OpenCode AGENTS.md entry from Cursor rule body.
 * The section carries a per-rule marker comment so reruns are idempotent.
 * @param ruleContent - Raw Cursor `.mdc` rule content.
 * @param ruleName - Rule name used in the marker and error messages.
 * @param existingContent - Existing AGENTS.md content, when present.
 * @returns AGENTS.md target and merged content.
 */
function renderCodexOrOpenCodeRule(
	ruleContent: string,
	ruleName: string,
	existingContent?: string,
): {
	target: string;
	content: string;
} {
	const { body } = parseCursorRuleDocument(ruleContent);
	const marker = `<!-- Generated by \`cheetos agent-instructions\` (${ruleName}) -->`;
	const section = `${marker}\n\n${body}`;

	if (existingContent && existingContent.trim().length > 0) {
		if (existingContent.includes(marker))
			return { target: "AGENTS.md", content: existingContent };

		return {
			target: "AGENTS.md",
			content: `${existingContent.trimEnd()}\n\n---\n\n${section}\n`,
		};
	}

	return {
		target: "AGENTS.md",
		content: `${section}\n`,
	};
}

/**
 * Render an agent rule for the requested coding agent or IDE format.
 * @param ruleContent - Raw Cursor `.mdc` rule content.
 * @param ruleName - Normalized rule name (e.g. `code-standards`).
 * @param codingAgentIDE - Chosen target format from conditions.
 * @param existingTargetContent - Optional existing file content when merging files like AGENTS.md.
 * @returns Target file path and rendered content.
 */
export function renderAgentRule(
	ruleContent: string,
	ruleName: string,
	codingAgentIDE: SupportedCodingAgentIDE,
	existingTargetContent?: string,
): { target: string; content: string } {
	switch (codingAgentIDE) {
		case "cursor":
			return renderCursorRule(ruleContent, ruleName);
		case "claude-code":
			return renderClaudeCodeRule(ruleContent, ruleName);
		case "copilot":
			return renderCopilotRule(ruleContent, ruleName);
		case "codex":
		case "opencode":
			return renderCodexOrOpenCodeRule(
				ruleContent,
				ruleName,
				existingTargetContent,
			);
		default: {
			const exhaustive: never = codingAgentIDE;
			throw new Error(`Unhandled IDE format "${String(exhaustive)}".`);
		}
	}
}

/**
 * Decide whether a compiled file is a rule source (a `.cursor/rules/*.mdc` target).
 * @param file - Compiled item file.
 * @returns True when the file targets Cursor's rules directory with the `.mdc` suffix.
 */
function isRuleFile(file: CompiledItemFile): boolean {
	return file.target.startsWith(".cursor/rules/") && file.target.endsWith(".mdc");
}

/**
 * Derive the rule name from a `.cursor/rules/*.mdc` target.
 * @param target - Compiled rule target.
 * @returns Rule name (stem without `.mdc`).
 */
function ruleNameFromTarget(target: string): string {
	return target.split("/").pop()?.replace(/\.mdc$/, "") ?? "";
}

/**
 * Merge every rule of an item into the AGENTS.md content for codex/opencode.
 * @param ruleFiles - Every `.cursor/rules/*.mdc` compiled file of the item.
 * @param codingAgentIDE - Target IDE (`codex` or `opencode`).
 * @param existingTargetContent - Optional existing AGENTS.md content.
 * @returns One AGENTS.md render carrying a section per rule.
 */
function renderAgentsMdForRules(
	ruleFiles: CompiledItemFile[],
	codingAgentIDE: SupportedCodingAgentIDE,
	existingTargetContent: string | undefined,
): { target: string; content: string } {
	// Fold the rules into one AGENTS.md by chaining the merge: each render
	// consumes the previous render's output as the "existing" content.
	return ruleFiles.reduce(
		(merged, file, index) =>
			renderAgentRule(
				file.content,
				ruleNameFromTarget(file.target),
				codingAgentIDE,
				index === 0 ? existingTargetContent : merged.content,
			),
		{ target: "AGENTS.md", content: existingTargetContent ?? "" },
	);
}

/** `beforeWrite` hook that transforms Cursor `.mdc` rule files for the selected IDE format. */
const transformAgentRuleForIde: BeforeWriteHook = async (ctx) => {
	const codingAgentIDERaw = ctx.conditions.codingAgentIDE;
	if (typeof codingAgentIDERaw !== "string" || !SUPPORTED_CODING_AGENT_IDES.has(codingAgentIDERaw)) {
		throw new Error(
			`Condition "codingAgentIDE" must be one of ${[...SUPPORTED_CODING_AGENT_IDES].join(", ")} to install rule "${ctx.itemId}".`,
		);
	}

	// Default target in files is already Cursor format: no-op when Cursor is chosen
	if (codingAgentIDERaw === "cursor") return;

	const ruleFiles = ctx.compiledItem.files.filter(isRuleFile);
	if (ruleFiles.length === 0) {
		throw new Error(
			`Item "${ctx.itemId}" has no .cursor/rules/*.mdc source file to transform.`,
		);
	}

	let existingTargetContent: string | undefined;
	const workingAgentsMd = ctx.compiledItem.files.find(
		(file) => file.target === "AGENTS.md",
	);
	if (workingAgentsMd) existingTargetContent = workingAgentsMd.content;
	else if (
		(codingAgentIDERaw === "codex" || codingAgentIDERaw === "opencode") &&
		(await ctx.isFile("AGENTS.md"))
	) {
		try {
			existingTargetContent = await ctx.readFile("AGENTS.md");
		} catch {
			// Ignore read error
		}
	}

	if (codingAgentIDERaw === "codex" || codingAgentIDERaw === "opencode") {
		// All rules fold into one AGENTS.md with a section per rule.
		const rendered = renderAgentsMdForRules(
			ruleFiles,
			codingAgentIDERaw as SupportedCodingAgentIDE,
			existingTargetContent,
		);
		return {
			files: [rendered],
			removeFiles: ruleFiles.map((file) => file.target),
		};
	}

	// Transform every rule file. Rule files are found by `.cursor/rules/`
	// target, never by array index, so ordering in the item manifest is free.
	const renderedRules = ruleFiles.map((file) =>
		renderAgentRule(
			file.content,
			ruleNameFromTarget(file.target),
			codingAgentIDERaw as SupportedCodingAgentIDE,
		),
	);

	return {
		files: renderedRules,
		removeFiles: ruleFiles.map((file) => file.target),
	};
};

export default transformAgentRuleForIde;
