name: Test (Coverage)

on:
  push:
    branches:
      - {{defaultBranch}}
  pull_request:
    branches:
      - {{defaultBranch}}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  test:
    name: Test (Coverage)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup workspace
        uses: ./.github/actions/setup

      - name: Run tests with coverage
        run: {{pmRun}} cov
