sonar.projectKey={{sonarProjectKey}}
sonar.organization={{sonarOrganization}}
sonar.sources=src
sonar.tests=src
sonar.exclusions=**/dist/**,**/build/**,**/coverage/**
sonar.coverage.exclusions=**/test/**,**/tests/**,**/*test*,**/*spec*
